### ISSUE TITLE
feature request: show thousands separator and percentage for stats

### ISSUE THREAD

**Issue by cachho** [jnbarlow/monero-dashboard#10]
Right now we have:

```
Difficulty                 1319321123
Height                     102392 
Target Height              3082454
```

From this it's hard to read how much you have synced.

I'd like it to be something like this for readability.

```
Difficulty                      1319321123
Height                             102,392 
Target Height                    3,082,454
Sync Percentage                       3.3%
```

So:

- add a percentage
- text right
- thousands separator (could also use `toLocaleString()`)

**Comment by jnbarlow** [comment]
I like it. let me see what I can do :)
